version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce
    hostname: "gitlab.example.com"
    volumes: 
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    ports:
      - 443:443
      - 80:80
      - 22:22
    networks:
      laptop:
        ipv4_address: 172.16.1.2
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.16.1.5:5140"


  jenkins:
    image: jenkins
    hostname: "jenkins.example.com"
    volumes:
      - /srv/jenkins/jenkins_home:/var/jenkins_home
    ports:
      - 8080
      - 50000
    networks:
      laptop:
        ipv4_address: 172.16.1.3
    depends_on:
      - logstash
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.16.1.5:5140"

  elasticsearch: 
    image: elasticsearch
    hostname: "es.example.com"
    ports:
      - 9200
      - 9300
    expose:
      - 9200
      - 9300
    networks:
      laptop: 
        ipv4_address: 172.16.1.4
    volumes:
      - /srv/elasticsearch/config:/usr/share/elasticsearch/config
      - /srv/elasticsearch/data:/usr/share/elasticsearch/data
 
  logstash:
    image: logstash 
    command: "logstash -f /etc/logstash/conf.d/logstash.conf"
    hostname: "logstash.example.com"
    ports:
      - 5140
    expose:
      - 5140
    networks:
      laptop:
        ipv4_address: 172.16.1.5
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - /srv/logstash/conf.d:/etc/logstash/conf.d
      - /srv/logstash/logs:/var/log/logstash

  kibana:
    image: kibana 
    hostname: "kibana.example.com"
    ports:
      - 5601
    networks:
      laptop:
        ipv4_address: 172.16.1.6
    depends_on:
      - elasticsearch
    links:
      - elasticsearch 

  puppetserver:
    image: puppet/puppetserver 
    hostname: "puppet"
    ports:
      - 8140
    volumes:
      - /srv/puppetserver/code:/etc/puppetlabs/code/
      - /srv/puppetserver/puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - /srv/puppetserver/puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/
    networks:
      laptop:
        ipv4_address: 172.16.1.7
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.16.1.5:5140"

  puppetdbpostgres:
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    ports:
      - 5432
    volumes:
      - /srv/puppetdbpostgres/data:/var/lib/postgresql/data/
    networks:
      laptop:
        ipv4_address: 172.16.1.8
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.16.1.5:5140"

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb
    ports:
      - 8080
      - 8081
    volumes:
      - /srv/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
    networks:
      laptop:
        ipv4_address: 172.16.1.9
    links:
      - puppetserver:puppet
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.16.1.5:5140"

  puppetboard:
    image: puppet/puppetboard
    ports:
      - 8000
    networks:
      laptop:
        ipv4_address: 172.16.1.10

  puppetexplorer:
    image: puppet/puppetexplorer
    ports:
      - 80
    read_only: true
    networks:
      laptop:
        ipv4_address: 172.16.1.11
  
  puppetagent:
    image: puppet/puppet-agent-centos
    links:
      - puppetserver:puppet
    networks:
      laptop:
        ipv4_address: 172.16.1.12

  puppetagent-ubuntu:
    image: puppet/puppet-agent-ubuntu
    links:
      - puppetserver:puppet
    networks:
      laptop:
        ipv4_address: 172.16.1.13
  

networks:
  laptop:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/16
          gateway: 172.16.1.1
